---
title: "games_sales_app_hw"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(ggplot2)

games_sales <- CodeClanData::game_sales

```
```{r}
games_sales_piv %>% 
 filter(review_type == "user_critic_avg") %>% 
  slice_max(review_score)
```



```{r}
games_sales_piv <- games_sales %>% 
  mutate(user_score = user_score * 10) %>% 
  mutate(user_critic_avg = (user_score + critic_score) / 2, .after = user_score) %>% 
pivot_longer(cols = critic_score:user_critic_avg,
             names_to = "review_type",
             values_to = "review_score") %>%
arrange(name)
```


```{r}
games_sales_genre <- games_sales_piv %>% 
  distinct(genre) %>% 
  pull()
```

```{r}
games_sales_console <- games_sales_piv %>% 
  distinct(platform) %>% 
  pull()
```





```{r}
# input <- list("critic_score",
#            "user_score",
#            "user_critic_avg")


games_sales_piv %>%
  filter(genre == "Racing") %>% 
  filter(platform == "PS4") %>% 
  filter(review_type == "critic_score")
  ## input
  # slice_max(review_score) %>% 
  # ggplot() +
  # aes(x = name, y = review_score, fill = platform) +
  # geom_col(position = "dodge") +
  # coord_flip()

  
```

```{r}
games_review_type <- games_sales_piv %>% 
  distinct(review_type) %>% 
  pull()
```



```{r}
oom <- CodeClanData::olympics_overall_medals

```

